# Generated by Django 4.2.6 on 2023-11-10 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='patronymic',
            field=models.CharField(max_length=150, verbose_name='patronymic'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='tel',
            field=models.CharField(help_text='Example: +7(XXX)-XXX-XX-XX', max_length=24, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('declined', 'declined')], default='new', max_length=10, verbose_name='status'),
        ),
    ]
